language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python tests.py
services:
- mongodb
notifications:
  slack:
    secure: P1g8v2JrPv/VkYzcdbzYpg/2GSpsWrfd6cBj3totxofO2ghEaLVewScxk06QURNouNBzjYGhTiK2tdHlQC30CbolpCzmM7iWjqf3rxZDQIMlEQtNn6MdKFrDaFgTfeI25kMCcfkEzbcyGQZCUJ8BKmngnlzyL8GdB/SnDluSnmGkvIT6iQ4QW9OAQ0Kx/7TKDcUsLu+DvfACj6aGneP1PGHRyiMljAmaIRox9+QBGD8OKKa3pivE3LTMju2Ju3QOvpVYGZCrro+0eW9cdidPeY5p8rxEQr4KXmfYkagS/dXnfqvvuE3UU4j4q+IO/I7rmTpoFEM7fvbJ3ygZtctWPZ1IL5XYyJt0WNqLIOHVPshYbvHrU2PN85KJMQaYTasq0Bmkqu2jxYHXFwxiEU2wR4gM3GfzpZ/ZfNWGOaFKDOw1e6aWuQBN6ahqtaVly5nOU9LWJVqQKJVM1tEfCnyfSmrK3w3+Fl7gjyxIkKjetar+pRVWLYH9NwNVALGAPWdT0qyFHvn16EzOK7tz7QT+/Qc72vtqp6d04qrVnHJWbWrAF8w/68WDAXuty83c6oTAvLhZojVUVj3/4RksDnTUTCNjIV6ZbxykExcGlsP5wh0yrIijEpJNNXqBhyFbAs+cNDznq2WBRC0z92QMfFwaOUwTIhTGPSSMh8/cGWIsBwA=
deploy:
  provider: heroku
  api_key:
    secure: H01WOmiMhDiCBrocqLDrq7/yJObqPzAHdlfl+lSdwPl1nYzhfhh6MUfQIFBfvw53htLTJwvpA/FCVJOmN5TdGMVeBsAf7k7CYABcijelmBZWjgDyqeJxYXBnjI6L7oP5pNpimcA04BTY7kErgCO1DPTIjHiZ7xmbUzlm3UulhYDWOtSLiRZFxCsXr6uE7f4Kex0fFSEHhTqvkxKRQXyux0qdyODZ3yhakU5J+R8cMjj4v/BX7ewOSkAMe9JalVb0RD5l63MeZzNZl4J7Yn4VT9gvnFbMZ+93SERE095963IvtraA05se/uLAb0ZsPdH669Su5zb9GlnYI31dpPf87ecY8VK1RAAaQUKQFQhyYupy2VOnn2XqEAPl0EF/L8ar1jq8vtJ18We+U8SxIrX/ZRplqPJxDz9n0EsMvP4BlYoxGukCBvdilJaA5p2uJV25G8Qqn4ghvW+20o3CFmnESJSm6N7dd8rC4cu0NkKI/gCmcUO10LGMDMj/Z5ryBHW79rnHvIkk9LWDOo9gGZu4+iHyClg3gcq5sUDmqUNg/MQmb3OaGojYq9iGSEUF63t6u7FeujbHT6Quie0YWaQy82khSYALKYdGOuy3FoUTP1JX5Zs8R6hvWBl98m5va6cmlwPK8ZCUqCXk4oUuet3YK+ZhSx4xYkkrgHrzXoDZ7To=
  app: national-library-service
  on:
    repo: Doteveryone/NationalLibraryService
